<!DOCTYPE html>
<html lang="br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Teste RH - Levelup">
        <meta name="author" content="Eric Lemes">
        <link rel="icon" href="images/favicon.ico">
        <title>Teste - Levelup</title>
        <!-- Bootstrap core CSS -->
        <link href="bootstrap-3.3.2/css/bootstrap.min.css" rel="stylesheet">
        <link href="css/base.css" rel="stylesheet">
        <script src="bootstrap-3.3.2/js/ie-emulation-modes-warning.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.min.js"></script>
    </head>
    <body>

        <!-- Menu navbar -->
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#" onclick="link('index/principal')">
                        <img class="logo" src="images/logo.png" width="100" height="30"/>
                    </a>
                </div>

                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="javascript:void(0);" onclick="link('index/principal')">Home</a></li>
                        <li><a href="javascript:void(0);" onclick="carrinho_()">Carrinho</a></li>
                    </ul>

                    <!-- Carrinho superior -->
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a class="dropdown-toggle" aria-expanded="false" role="button" data-toggle="dropdown" href="">
                                <span class="glyphicon glyphicon-shopping-cart"></span>
                                <span class="badge" id="carrinho_total">0</span>
                                <span class="caret" id="carrinho_totalpg"></span>
                            </a>

                            <!-- Carrinho down -->
                            <ul class="dropdown-menu dropdown-cart" id="carrinho" role="menu">
                            </ul>

                        </li>
                    </ul>
                </div>

            </div>
        </nav>

        <!-- Div conteudo load-->
        <div class="container" id="conteudo">
        </div>

        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script src="bootstrap-3.3.2/js/bootstrap.min.js"></script>
        <script src="js/script.js"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="bootstrap-3.3.2/js/ie10-viewport-bug-workaround.js"></script>
    </body>
</html>